### ISSUE TITLE
[상품] 관리자는 판매할 상품을 판매상태(품절)를 변경 할 수 있습니다.

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/shop-SSG-Town-Store#11]
## 🌈 Success criteria 

1. 관리자는 인증 후 상품관리 메뉴에서 상품의 판매상태를 품절로 변경 할 수 있습니다. 
2. 도서 등록 Dao처리는 테스트코드로 검증해야합니다.

## 👷To-do

- [x] 1. 상품삭제 기능(updateSaleStatus()) 구현 
- [x] 관리자는 판매 상태가 품절인 경우 판매중지로 변경 할 수 있습니다.
- [x] 삭제 처리는 삭제 버튼을 눌렀을 때 주문DB에 update 됩니다. (POST)
- [x] 삭제가 실패하면 (이미 상태가 판매중지,판매중인 주문건을 삭제하려고 하는 경우) "품절상태가 아닙니다."  모달창이 뜹니다.
- [x] 휴지통버튼을 누르면 상품관리페이지(item/list)로 이동합니다. (리다이렉트)
- [x] 상품삭제 기능 테스트

**Comment by nnieun** [comment]
[Feat: 상품상태변경 Dao 추가](https://github.com/nnieun/shop-SSG-Town-Store/commit/643fbc86b3474add56b583795401bfc86ff3c877)https://github.com/ssg-java3-240304/shop-SSG-Town-Store/issues/11

상품상태변경 Dao Test추가 입니다 커밋메세지 잘 못 썼어요
