### ISSUE TITLE
[로그인] 관리자는 로그인페이지에서 아이디와 비밀번호를 입력해 로그인 할 수 있습니다.

### ISSUE THREAD

**Issue by yongjun98** [ssg-java3-240304/shop-SSG-Town-Store#20]
## 🌈 Success criteria 

1. 로그인 폼을 구성합니다
2. DB의 관리자 테이블을 조회하여 입력된 아이디와 비밀번호가 일치하는지 로그인자격을 검증합니다
3. 인증 성공 시 관리자를  메인페이지로 리다이렉트 하고 메세지를 출력합니다.  (alert : 로그인에 성공하셨습니다!). 
4. 인증 실패시, 로그인 페이지에 오류 메세지를 표시합니다(alert : 로그인에 실패하셨습니다. 로그인 정보를 다시 확인해 주세요!).
## 👷To-do

- [x] GET/login.html을 작성합니다. 
- [x] 로그인 관련 db를 만들고 데이터를 삽입합니다. 
- [x] 로그인 처리 결과에 따른 alert()를 작성합니다.
