### ISSUE TITLE
[회원]관리자는 회원관리 페이지에서 회원상태에 따라  회원을 목록에서 삭제 할 수 있습니다

### ISSUE THREAD

**Issue by yongjun98** [ssg-java3-240304/shop-SSG-Town-Store#23]
## 🌈 Success criteria 

1. 회원이 탈퇴를 한경우 회원 탈퇴여부 상태가 'Y' 로 바뀝니다.
2. 관리자가 탈퇴한 회원에 대해 삭제 버튼을 클릭하면, 확인 팝업이 나타나며  관리가 확인을 선택합니다
3. 삭제 요청이 서버로 전송되어 DB에서 해당 회원 정보가 삭제됩니다
4. 삭제 완료 후 삭제 완료 메시지가 반환됩니다.

## 👷To-do

- [ ] 회원삭제에 대해 2차 확정을 위한 알림팝업을 작성합니다.
- [ ] 특정회원을 db에서 삭제할 쿼리문을 작성합니다. 
- [ ] 삭제 후 삭제완료 메세지를 위한 alert()를 작성합니다.
