### ISSUE TITLE
[매출] 관리자는 주문에 대하여 매출 조회를 할 수 있습니다.

### ISSUE THREAD

**Issue by dohwani** [ssg-java3-240304/shop-SSG-Town-Store#27]
## 🌈 Success criteria 

1. 관리자가 모든 주문에 대해 상품(앨범 또는 굿즈), 아티스트, 구매자의 성별, 나이대, 금액별로 총 매출을 조회할 수 있는 기능을 구현합니다.

## 👷To-do

- [x] 할일 1 sales에 필요한 필드 추가
- [x] 할일 2 salesRepository 인터페이스에 쿼리 메소드 추가
- [x] 할일 2 Sales service 클래스에 매출 조회 메소드 작성
- [x] 할일 3 Sales controller 클래스에 매출 조회 엔드포인트 작성
- [x] 할일 4 매출 조회 결과를 표시할 html 페이지 작성
