### ISSUE TITLE
[매출] 관리자는 기간별 매출이 높은 상품을 조회할 수 있습니다.

### ISSUE THREAD

**Issue by dohwani** [ssg-java3-240304/shop-SSG-Town-Store#28]
## 🌈 Success criteria 

1. 기간별로 매출이 높은 앨범을 필터링하고 정렬할 수 있어야 합니다.

## 👷To-do

- [ ] 할일 1 SalesService 클래스에 기간별 매출 조회 메소드 작성
- [ ] 할일 2 SalesController 클래스에 매출 조회 엔드포인트 작성
- [ ] 할일 3 매출 조회 결과를 표시할 html 페이지 작성
