### ISSUE TITLE
[매출] 관리자는 가장높은 매출의 앨범 TOP10을 그래프로 조회할 수 있다.

### ISSUE THREAD

**Issue by dohwani** [ssg-java3-240304/shop-SSG-Town-Store#29]
## 🌈 Success criteria 

1. 기간별 ,월별, 분기별로 데이터를 필터링하고 매출 TOP10의 앨범을 그래프로 조회 할 수 있다.
2. graph.js 의 템플릿을 가져와 코드분석후 대입해야 하는 작업

## 👷To-do

- [ ] 할일 1 SalesService 클래스에 Top 10 매출 앨범 조회 메소드 작성
- [ ] 할일 2 SalesController 클래스에 그래프 조회 엔드포인트 작성
- [ ] 할일 3 Top 10 매출 앨범을 그래프로 표시할 HTML 페이지 작성
- [ ] 할일 4 JavaScript 라이브러리를 이용하여 그래프 구현
