### ISSUE TITLE
[상품] 관리자는 조건에 맞는 상품을 검색할 수 있습니다.

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/shop-SSG-Town-Store#8]
## 🌈 Success criteria 

1. 관리자는 상품명을 수기로 작성해 검색할 수 있습니다.
2. [조건검색] 창을 선택하면, 조건폼이 펼쳐집니다.
3. (카테고리명, 아티스트명, 가격) 중 필터링 조건을 중복선택할 수 있습니다.
4. 선택한 조건에 맞는 상품만 보여줍니다.
5. 조회된 상품이 없으면 테이블 위치에 비어있는 화면을 보여줍니다.
6. 조회 후 다시 검색할 수 있습니다.

## 👷To-do

- [x] 1. 상품 조회에 필요한 쿼리작성 후, Dao Mapper 테스트를 작성합니다.
- [x] 2. 상품을 중복 조건 조회하는 검색폼을 구현합니다. 
- [x] 3. 선택한 조건이 일치하는 상품 목록만 보여주는 findAllMatch()를 구현합니다.
- [x] 6. Controllr는 필터링한 ItemDto객체만 Get/item/list로 model객체에 전달합니다.
- [x] 7. html은 ItemDto를 테이블 형식으로 보여줍니다.

**Comment by vlshzl35** [comment]
강사님 피드백
도전해봤는데 해결을 못해서 To-do로 남김
- [ ] list.html에서 enum타입 select옵션으로 불러오는 것 구현하기
- [ ] 상세 조건창 깔때기 항상 내려와있게 하기 (No hidden)
- [ ] 상세 페이지 링크달기
- [ ] 조건 선택한 것 검색 후에도 기억하기
