### ISSUE TITLE
[상품] 관리자는 판매할 상품정보를 등록할 수 있습니다.

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/shop-SSG-Town-Store#9]
## 🌈 Success criteria 

1. 관리자는 인증 후 상품관리 메뉴에서 상품을 등록 할 수 있습니다.
2. 도서 등록 Dao처리는 테스트코드로 검증해야합니다.

## 👷To-do

- [x] 1. 상품등록페이지 화면 구현 - (item/create) 화면 구현
- [x] 2. 상품등록 등록기능(createItem()) 구현 
- [x] 상품등록 버튼을 누르면 상품등록페이지(item/create)로 이동합니다. (GET)
- [x] 등록할 때 관리자가 입력할 값은  (상품명, 카테고리명, 아티스트명, 이미지, 세부설명, 수량, 가격)에 대해 입력합니다. (상품명, 카테고리명, 아티스트명, 이미지,수량, 가격) 필수 이며, 세부설명은 선택입니다. (이때 테이블과 맞지 않는 조건들을 각각 검증합니다.)
- [x] 등록 처리는 등록 버튼을 누를시 (상품ID는 auto, 판매상태 default 판매중,판매원은 defalut SSG)으로 자동 생성되며 입력된 정보값은 상품테이블에 삽입됩니다. (POST)
- [x] 등록이 완료되면 상품관리페이지(item/list)로 이동합니다. (GET)
- [x] 상품등록 등록기능 테스트

**Comment by vlshzl35** [comment]
To-do
1. 상품 이미지를 base64 인코딩으로 받는 것이 아닌 FTP 서버에 저장해 모든 PC에서 등록한 이미지를 받아올 수 있도록 구현
2. 여러폼을 사용해 입력값을 받을때 마지막 폼에서 모든 입력을 가져와 한번에 제출하는 것이 아닌 다른 좋은 방법이 있을까
